name: weather_forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h540bb41_1
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.0=h91e5215_2
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h9214b88_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=pyh7db6752_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - kiwisolver=1.4.8=py312h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h6470a55_1
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h7351971_1
  - libpq=17.6=h652a1e2_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - matplotlib=3.10.6=py312haa95532_1
  - matplotlib-base=3.10.6=py312h43afe63_1
  - mkl=2025.3.0=hac47afa_454
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy=2.3.4=py312h050da96_1
  - numpy-base=2.3.4=py312h1e017a8_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h42c1672_1
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py312h4212202_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=6.9.1=py312h12ec796_0
  - pyqt6-sip=13.10.2=py312h630b2a1_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - qtbase=6.9.2=h06bae2a_4
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - rav1e=0.7.1=ha073cba_3
  - scikit-learn=1.7.1=py312h3fbe716_0
  - scipy=1.16.3=py312hbd6d557_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py312haa95532_0
  - sip=6.12.0=py312h706e071_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - statsmodels=0.14.5=py312hf9130e5_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py312h02ab6af_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - alembic==1.17.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - clearml==2.0.2
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - dill==0.4.0
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fsspec==2025.10.0
      - furl==2.1.4
      - greenlet==3.2.4
      - humanfriendly==10.0
      - hummingbird-ml==0.4.11
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lightgbm==4.3.0
      - mako==1.3.10
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - onnx==1.16.0
      - onnxconverter-common==1.16.0
      - onnxmltools==1.12.0
      - onnxruntime==1.18.0
      - optuna==4.5.0
      - orderedmultidict==1.0.1
      - pathlib2==2.3.7.post1
      - protobuf==6.33.0
      - pyjwt==2.10.1
      - pyreadline3==3.5.4
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - skl2onnx==1.17.0
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - torch==2.9.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
prefix: C:\Users\dohuu\miniconda3\envs\weather_forecast
